### ISSUE TITLE
Locale-specific Hello World

### ISSUE THREAD

**Issue by Alonso-del-Arte** [Alonso-del-Arte/toy-examples#5]
`greeting()` in `org.example.HelloWorld` should return an appropriate "Hello World" greeting for each of the named `Locale` constants in the `java.util.Locale` Javadoc (JDK 8) https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html Write tests in `HelloWorldTest` first.

**Comment by iremugurlu** [comment]
Hey, I'm interested. Can you assign this one to me?

**Comment by Alonso-del-Arte** [comment]
Note: you may use Google Translate to look things up for the tests, but `HelloWorld` should not use any external APIs. Tests in `HelloWorldTest` need to precede the solution.

**Comment by Alonso-del-Arte** [comment]
Thank you Tomáš Kořónek (David S. Pumpkins)
